title: Константин Брызгин
author:
  name: k.bryzgin
  email: k.bryzgin@yandex.ru

description: >
  Изучаю анализ данных и машинное обучение.
  
logo: /assets/img/photo_gh.png
show_downloads: true
theme: jekyll-theme-minimal
