# title: Константин Брызгин
# author:
#   name: k.bryzgin
#   email: k.bryzgin@yandex.ru

# description: >
#   Вкатываюсь в DA, DS и ML
  
# logo: /assets/img/photo_gh.png
# show_downloads: true
remote_theme: "jekyll/minima@1e8a445"
